# Generated by Django 4.0.4 on 2022-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperating',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='reciperating',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 1), ('rate__lte', 5)), name='rate_validation'),
        ),
        migrations.AddConstraint(
            model_name='reciperating',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_user_per_recipe'),
        ),
    ]
